{% set name = "pylsewave" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
 git_url: https://github.com/giorgosR/pylsewave.git
 git_tag: 1.0.2
 
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - matplotlib
    - scipy
    - cython>=0.24.1
    - cymem
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - cython>=0.24.1
    - cymem
test:
  # Python imports
 imports:
    - pylsewave
    - pylsewave.cynum
 files:
    - cynum.pyx

about:
  home: https://github.com/giorgosR/pylsewave
  license: GPL-3.0 License
  license_family: GPL
  license_file: LICENSE
  summary: pylsewave
  description: A Python package to solve pulse wave dynamics in arterial networks
#  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/giorgosR/pylsewave

extra:
  recipe-maintainers:
    - giorgosR